---
functional:
  - Возможность регистрации с помощью электронной почты
  - Возможность авторизации с помощью Github
  - Возможность авторизации с помощью Discord
  - Возможность просматривать рейтинг участников проекта
  - Возможность просмотра архивных игр
  - Возможность воспроизведения повтора архивных игр
  - Возможность использовать разные языки программирования
  - Возможность просмотра активной игры зрителями в реальном времени
  - Возможность создания турниров по индивидуальному сценарию
  - Возможность приглашать в игру пользователей
  - Возможность участвовать в игре с ботом
  - Возможнсоть выбрать игру по уровню сложности
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователей
  - Сайт должен быть адаптирован для мобильных устройств
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Возможность сохранять повторы архивных игр в закладки в профиле поьзователя
  - Использование русской локализации сайта проекта
